//
//  MockData.swift
//  Samplero
//
//  Created by DaeSeong on 2022/10/09.
//

import Foundation

struct MockData {

    static let sampleList: [Sample] = [
        Sample(id: 0,
               matName: "스노우 화이트 (안심매트)",
               imageName: "ThumbnailFloriaSnowWhite",
               matPrice: -1,
               samplePrice: 0,
               material: "프리미엄 TPU 필름, PU폼",
               thickness: 2.3,
               size: CGSize(width: 50, height: 50),
               maker: "플로리아매트"),
        Sample(id: 1,
               matName: "화이트마블 (안심매트)",
               imageName: "ThumbnailFloriaWhiteMarble",
               matPrice: -1,
               samplePrice: 0,
               material: "프리미엄 TPU 필름, PU폼",
               thickness: 2.3,
               size: CGSize(width: 50, height: 50),
               maker: "플로리아매트"),
        Sample(id: 2,
               matName: "베이지마블 (안심매트)",
               imageName: "ThumbnailFloriaBeigeMarble",
               matPrice: -1,
               samplePrice: 0,
               material: "프리미엄 TPU 필름, PU폼",
               thickness: 2.3,
               size: CGSize(width: 50, height: 50),
               maker: "플로리아매트"),
        Sample(id: 3,
               matName: "밀크코튼 (안심매트)",
               imageName: "ThumbnailFloriaMilkCotton",
               matPrice: -1,
               samplePrice: 0,
               material: "프리미엄 TPU 필름, PU폼",
               thickness: 2.3,
               size: CGSize(width: 50, height: 50),
               maker: "플로리아매트"),
        Sample(id: 4,
               matName: "밀크티 (구름매트)",
               imageName: "ThumbnailFloriaMilkTea",
               matPrice: 14_900,
               samplePrice: 0,
               material: "프리미엄 TPU 필름, PU폼",
               thickness: 2.5,
               size: CGSize(width: 50, height: 50),
               maker: "플로리아매트"),
        Sample(id: 5,
               matName: "프리미엄 실리터치 화이트마블",
               imageName: "ThumbnailBomBomWhiteMarble",
               matPrice: 23_000,
               samplePrice: 0,
               material: "TPU, 고밀도 우레탄, 실리콘 코팅필름",
               thickness: 2.5,
               size: CGSize(width: 50, height: 50),
               maker: "봄봄매트"),
        Sample(id: 6,
               matName: "프리미엄 실리터치 코지베이지",
               imageName: "ThumbnailBomBomCozyBeige",
               matPrice: 23_000,
               samplePrice: 0,
               material: "TPU, 고밀도 우레탄, 실리콘 코팅필름",
               thickness: 2.5,
               size: CGSize(width: 50, height: 50),
               maker: "봄봄매트"),
        Sample(id: 7,
               matName: "프리미엄 실리터치 코지그레이",
               imageName: "ThumbnailBomBomCozyGray",
               matPrice: 23_000,
               samplePrice: 0,
               material: "TPU, 고밀도 우레탄, 실리콘 코팅필름",
               thickness: 2.5,
               size: CGSize(width: 50, height: 50),
               maker: "봄봄매트")
    ]
    
    static let estimateHistories: [EstimateHistory] = [
        EstimateHistory(imageId: 0,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil),
        EstimateHistory(imageId: 1,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil),
        EstimateHistory(imageId: 2,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil),
        EstimateHistory(imageId: 3,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil),
        EstimateHistory(imageId: 4,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil),
        EstimateHistory(imageId: 5,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil),
        EstimateHistory(imageId: 6,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil),
        EstimateHistory(imageId: 7,
                        width: nil,
                        height: nil,
                        selectedSampleId: nil)
    ]
}
